# Generated by Django 4.0.5 on 2022-06-27 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('area_name', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('tla', models.CharField(max_length=8, null=True, unique=True)),
                ('short_name', models.CharField(max_length=256, null=True)),
                ('area_name', models.CharField(max_length=256, null=True)),
                ('email', models.CharField(max_length=256, null=True)),
                ('competition', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='matches.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('position', models.CharField(max_length=256)),
                ('date_of_birth', models.DateField(null=True)),
                ('country_of_birth', models.CharField(max_length=256, null=True)),
                ('nationality', models.CharField(max_length=256, null=True)),
                ('team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='matches.team')),
            ],
        ),
    ]
