version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - internal

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - internal
    # for ipdb
    stdin_open: true
    tty: true

networks:
  internal:
    driver: bridge

volumes:
  postgresql: {}
